version: "3"

services:
  db:
    # image: postgres
    build:
      context: ./mysql/
    container_name: MySQL
    volumes:
      - ./volumes/data/db:/var/lib/mysql/djangodb
    env_file:
      - .env
    # DBのコンテナのヘルスチェックを行う
    # mysqladmin(MySQLサーバーの管理を行うクライアントを使ってDBコンテナ自身(127.0.0.1)にpingを送ってヘルスチェックを行う
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      # ヘルスチェックのインターバルは10秒
      interval: 10s
      # タイムアウト時間は10秒
      timeout: 10s
      # リトライ回数は3回
      retries: 3
      # ヘルスチェックが失敗しても無視する時間は30秒
      start_period: 30s

  app:
    build:
      context: ./django/
    volumes:
      - tmp-data:/app/tmp
      - ./nginx/static:/app/static
      # テンプレーツをマウントする
      - ./django:/app
    env_file:
      - .env
    # 先にdbを起動してからappを起動する
    depends_on:
      db:
        # dbのヘルスチェックが終わってからappを起動させる
        condition: service_healthy

  nginx:
    build:
      context: ./nginx/
    volumes:
      - tmp-data:/app/tmp
      - ./nginx/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - app
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    links:
      - db
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  tmp-data: